name: Generate IRIS models
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'feat-*'
    tags:
      - v*
  workflow_dispatch:
    inputs:
      amqp-generator-version:
        description: 'AMQP generator version (=iris-maven version)'
        type: string
        required: false
        default: ''
jobs:
  models:
    name: Generate Java and TS models
    uses: globalid/.github/.github/workflows/java-iris-publish.yml@master
    with:
      amqp-generator-version: ${{ github.event.inputs.iris-generator-version }}
    secrets: inherit