name: Build
"on":
  push:
    branches:
      - '*'
    tags:
      - v*
  workflow_dispatch: null
jobs:
  test:
    runs-on: ubuntu-latest
    name: run-tests
    steps:
      - name: setup java
        uses: globalid/github-actions/java-setup@main
      - shell: sh
        run: mvn -B verify -ntp
